### ISSUE TITLE
Question regarding new approach to define DBC mapping

### ISSUE THREAD

**Issue by sophokles73** [eclipse/kuksa.val.feeders#59]
I have created a VSS overlay with the following definitions:
```yaml
Vehicle.Tachograph.Driver:
  type: branch
  instances:
  - Driver[1,2]
  description: Information about the driver(s) of a (commercial) vehicle.

Vehicle.Tachograph.Driver.Identification:
  datatype: string
  type: attribute
  description: The unique identification of a driver in a Member State.
  comment: |
    This fields is formatted according the definition for driverIdentification
    in COMMISSION REGULATION (EC) No 1360/2002 Annex 1b.
```
Now I would like to use the [new approach](https://github.com/eclipse/kuksa.val.feeders/blob/main/dbc2val/mapping.md) to map *signalA* to *Vehicle.Tachograph.Driver.Driver1.Identification* and *signalB* to *Vehicle.Tachograph.Driver.Driver2Identification*.

Can I simply also put a definition like the following into the overlay file?

```yaml
Vehicle.Tachograph.Driver.Driver1.Identification:
  datatype: string
  type: attribute
  dbc:
    signal: signalA

Vehicle.Tachograph.Driver.Driver2.Identification:
  datatype: string
  type: attribute
  dbc:
    signal: signalB
```
